uploads = []
generated = []

[[outputs]]
id = "W55uSCcm_jm66vaCIL5Fa"
uri = "file://PMG-OS-FINAL-BLUEPRINT-v2.md"
type = "text"
title = "PMG Group OS — Final Blueprint v2.0 (Complete)"

[[outputs]]
id = "iXFV0eykSwGMCmScvvsNR"
uri = "file://PMG-OS-FINAL-BLUEPRINT-v3.md"
type = "text"
title = "PMG Group OS — Final Blueprint v3.0 (Complete & Enriched)"

[[outputs]]
id = "6FBJHuawFCxRexyXYAwwk"
uri = "file://PMG-OS-FINAL-BLUEPRINT-v3.pdf"
type = "pdf"
title = "PMG Group OS — Final Blueprint v3.0 (PDF)"
