import { Router, type IRouter } from "express";
import { db, tasksTable, usersTable, knowledgeEntriesTable } from "@workspace/db";
import { eq, and, inArray, desc } from "drizzle-orm";

/**
 * Admin overview — real data for Operations (tasks + team) and Knowledge Base
 * (document library). KPIs derived from live counts. No hardcoded arrays.
 */

const router: IRouter = Router();

const DOC_CATEGORIES = ["SOPs", "Playbooks", "Templates", "Win/Loss Analysis"];

function cap(s: string): string {
  return s ? s.charAt(0).toUpperCase() + s.slice(1) : s;
}

router.get("/admin/overview", async (_req, res): Promise<void> => {
  const now = Date.now();
  const todayStart = new Date();
  todayStart.setHours(0, 0, 0, 0);

  const taskRows = await db.select().from(tasksTable).orderBy(desc(tasksTable.createdAt));
  const users = await db.select().from(usersTable);
  const userByName = new Map(users.map((u) => [u.name, u]));

  const isOverdue = (t: any) => !!t.dueDate && new Date(t.dueDate).getTime() < now && t.status !== "completed";

  const dueLabel = (t: any): string => {
    if (!t.dueDate) return "—";
    const d = new Date(t.dueDate);
    if (t.status !== "completed" && d.getTime() < now) return "Overdue";
    const dd = new Date(d);
    dd.setHours(0, 0, 0, 0);
    const diff = Math.round((dd.getTime() - todayStart.getTime()) / 86400000);
    if (diff === 0) return "Today";
    if (diff === 1) return "Tomorrow";
    return d.toLocaleDateString("en-US", { month: "short", day: "numeric" });
  };

  const tasks = taskRows.map((t) => ({
    id: t.id,
    task: t.title,
    assignee: t.assignedTo ?? "Unassigned",
    due: dueLabel(t),
    priority: t.priority,
    source: cap(t.domain ?? ""),
    status: isOverdue(t) ? "overdue" : t.status,
  }));

  const activeTasks = taskRows.filter((t) => t.status !== "completed").length;
  const overdueTasks = taskRows.filter(isOverdue).length;

  const teamMap = new Map<string, { name: string; tasks: number; completed: number; overdue: number }>();
  for (const t of taskRows) {
    const name = t.assignedTo ?? "Unassigned";
    if (!teamMap.has(name)) teamMap.set(name, { name, tasks: 0, completed: 0, overdue: 0 });
    const e = teamMap.get(name)!;
    if (t.status === "completed") e.completed++;
    else e.tasks++;
    if (isOverdue(t)) e.overdue++;
  }
  const team = [...teamMap.values()].map((m) => {
    const u = userByName.get(m.name);
    const role = u ? u.title ?? cap(u.role) : m.name.includes("AI") ? "AI Automation" : "Team Member";
    return { ...m, role };
  });

  const docRows = await db
    .select()
    .from(knowledgeEntriesTable)
    .where(and(eq(knowledgeEntriesTable.isActive, true), inArray(knowledgeEntriesTable.category, DOC_CATEGORIES)))
    .orderBy(desc(knowledgeEntriesTable.updatedAt));
  const documents = docRows.map((d) => ({
    id: d.id,
    title: d.title,
    category: d.category,
    updated: d.updatedAt ? new Date(d.updatedAt).toLocaleDateString("en-US", { month: "short", day: "numeric" }) : "—",
    autoGenerated: d.source === "ai",
  }));
  const catCounts = new Map<string, number>();
  for (const d of docRows) catCounts.set(d.category, (catCounts.get(d.category) ?? 0) + 1);
  const categories = DOC_CATEGORIES.map((c) => ({ name: c, count: catCounts.get(c) ?? 0 }));

  res.json({
    kpis: { activeTasks, overdueTasks, docs: docRows.length, teamSize: team.length },
    team,
    tasks,
    documents,
    categories,
  });
});

export default router;
