import { Router, type IRouter } from "express";
import healthRouter from "./health";
import companiesRouter from "./companies";
import contactsRouter from "./contacts";
import leadsRouter from "./leads";
import opportunitiesRouter from "./opportunities";
import activitiesRouter from "./activities";
import campaignsRouter from "./campaigns";
import tasksRouter from "./tasks";
import documentsRouter from "./documents";
import communicationsRouter from "./communications";
import dashboardRouter from "./dashboard";
import approvalsRouter from "./approvals";
import assetsRouter from "./assets";
import auditEventsRouter from "./audit-events";
import aiRunsRouter from "./ai-runs";
import archiveItemsRouter from "./archive-items";
import contractsRouter from "./contracts";
import invoicesRouter from "./invoices";
import integrationsRouter from "./integrations";
import outreachSequencesRouter from "./outreach-sequences";
import qualityIssuesRouter from "./quality-issues";
import reportsRouter from "./reports";
import usersRouter from "./users";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(companiesRouter);
router.use(contactsRouter);
router.use(leadsRouter);
router.use(opportunitiesRouter);
router.use(activitiesRouter);
router.use(campaignsRouter);
router.use(tasksRouter);
router.use(documentsRouter);
router.use(communicationsRouter);
router.use(approvalsRouter);
router.use(assetsRouter);
router.use(auditEventsRouter);
router.use(aiRunsRouter);
router.use(archiveItemsRouter);
router.use(contractsRouter);
router.use(invoicesRouter);
router.use(integrationsRouter);
router.use(outreachSequencesRouter);
router.use(qualityIssuesRouter);
router.use(reportsRouter);
router.use(usersRouter);

export default router;
